/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class ESet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ESet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ESet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ESet obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_ESet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ESet() {
    this(XapianJNI.new_ESet(), true);
  }

  public long size() {
    return XapianJNI.ESet_size(swigCPtr, this);
  }

  public boolean empty() {
    return XapianJNI.ESet_empty(swigCPtr, this);
  }

  public long getEbound() {
    return XapianJNI.ESet_getEbound(swigCPtr, this);
  }

  public ESetIterator begin() {
    return new ESetIterator(XapianJNI.ESet_begin(swigCPtr, this), true);
  }

  public ESetIterator end() {
    return new ESetIterator(XapianJNI.ESet_end(swigCPtr, this), true);
  }

  public ESetIterator back() {
    return new ESetIterator(XapianJNI.ESet_back(swigCPtr, this), true);
  }

  public String toString() {
    return XapianJNI.ESet_toString(swigCPtr, this);
  }

}
