/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class ExpandDeciderFilterPrefix extends ExpandDecider {
  private transient long swigCPtr;

  protected ExpandDeciderFilterPrefix(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.ExpandDeciderFilterPrefix_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExpandDeciderFilterPrefix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ExpandDeciderFilterPrefix obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_ExpandDeciderFilterPrefix(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ExpandDeciderFilterPrefix(String prefix_) {
    this(XapianJNI.new_ExpandDeciderFilterPrefix(prefix_), true);
  }

  public boolean accept(String term) {
    return XapianJNI.ExpandDeciderFilterPrefix_accept(swigCPtr, this, term);
  }

}
