/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class KeyMaker {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KeyMaker(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeyMaker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(KeyMaker obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_KeyMaker(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XapianJNI.KeyMaker_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XapianJNI.KeyMaker_change_ownership(this, swigCPtr, true);
  }

  public KeyMaker() {
    this(XapianJNI.new_KeyMaker(), true);
    XapianJNI.KeyMaker_director_connect(this, swigCPtr, true, true);
  }

  public String apply(Document doc) {
    return XapianJNI.KeyMaker_apply(swigCPtr, this, Document.getCPtr(doc), doc);
  }

  public KeyMaker release() {
    long cPtr = XapianJNI.KeyMaker_release(swigCPtr, this);
    return (cPtr == 0) ? null : new KeyMaker(cPtr, false);
  }

}
