/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class LMWeight extends Weight {
  private transient long swigCPtr;

  protected LMWeight(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.LMWeight_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LMWeight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LMWeight obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_LMWeight(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LMWeight(double param_log_, Weight.type_smoothing select_smoothing_, double param_smoothing1_, double param_smoothing2_) {
    this(XapianJNI.new_LMWeight__SWIG_0(param_log_, select_smoothing_.swigValue(), param_smoothing1_, param_smoothing2_), true);
  }

  public LMWeight(double param_log_, Weight.type_smoothing select_smoothing_, double param_smoothing1_) {
    this(XapianJNI.new_LMWeight__SWIG_1(param_log_, select_smoothing_.swigValue(), param_smoothing1_), true);
  }

  public LMWeight(double param_log_, Weight.type_smoothing select_smoothing_) {
    this(XapianJNI.new_LMWeight__SWIG_2(param_log_, select_smoothing_.swigValue()), true);
  }

  public LMWeight(double param_log_) {
    this(XapianJNI.new_LMWeight__SWIG_3(param_log_), true);
  }

  public LMWeight() {
    this(XapianJNI.new_LMWeight__SWIG_4(), true);
  }

  public String name() {
    return XapianJNI.LMWeight_name(swigCPtr, this);
  }

  public double getSumPart(long wdf, long doclen, long uniqterm) {
    return XapianJNI.LMWeight_getSumPart(swigCPtr, this, wdf, doclen, uniqterm);
  }

  public double getMaxPart() {
    return XapianJNI.LMWeight_getMaxPart(swigCPtr, this);
  }

  public double getSumExtra(long doclen, long arg1) {
    return XapianJNI.LMWeight_getSumExtra(swigCPtr, this, doclen, arg1);
  }

  public double getMaxExtra() {
    return XapianJNI.LMWeight_getMaxExtra(swigCPtr, this);
  }

}
