/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class PositionIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PositionIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PositionIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(PositionIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_PositionIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PositionIterator() {
    this(XapianJNI.new_PositionIterator(), true);
  }

  public void skipTo(long termpos) {
    XapianJNI.PositionIterator_skipTo(swigCPtr, this, termpos);
  }

  public String toString() {
    return XapianJNI.PositionIterator_toString(swigCPtr, this);
  }

  public boolean equals(PositionIterator o) {
    return XapianJNI.PositionIterator_equals(swigCPtr, this, PositionIterator.getCPtr(o), o);
  }

  public long getTermPos() {
    return XapianJNI.PositionIterator_getTermPos(swigCPtr, this);
  }

  public long next() {
    return XapianJNI.PositionIterator_next(swigCPtr, this);
  }

}
