/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class SimpleStopper extends Stopper {
  private transient long swigCPtr;

  protected SimpleStopper(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.SimpleStopper_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SimpleStopper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SimpleStopper obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_SimpleStopper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SimpleStopper() {
    this(XapianJNI.new_SimpleStopper__SWIG_0(), true);
  }

  public void add(String word) {
    XapianJNI.SimpleStopper_add(swigCPtr, this, word);
  }

  public boolean apply(String term) {
    return XapianJNI.SimpleStopper_apply(swigCPtr, this, term);
  }

  public String toString() {
    return XapianJNI.SimpleStopper_toString(swigCPtr, this);
  }

  public SimpleStopper(String file) {
    this(XapianJNI.new_SimpleStopper__SWIG_1(file), true);
  }

}
