/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class ValueIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ValueIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValueIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ValueIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_ValueIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ValueIterator() {
    this(XapianJNI.new_ValueIterator(), true);
  }

  public long getDocId() {
    return XapianJNI.ValueIterator_getDocId(swigCPtr, this);
  }

  public int getValueNo() {
    return XapianJNI.ValueIterator_getValueNo(swigCPtr, this);
  }

  public void skipTo(long docid_or_slot) {
    XapianJNI.ValueIterator_skipTo(swigCPtr, this, docid_or_slot);
  }

  public boolean check(long docid) {
    return XapianJNI.ValueIterator_check(swigCPtr, this, docid);
  }

  public String toString() {
    return XapianJNI.ValueIterator_toString(swigCPtr, this);
  }

  public String next() {
    return XapianJNI.ValueIterator_next(swigCPtr, this);
  }

  public boolean hasNext() {
    return XapianJNI.ValueIterator_hasNext(swigCPtr, this);
  }

  public boolean equals(ValueIterator o) {
    return XapianJNI.ValueIterator_equals(swigCPtr, this, ValueIterator.getCPtr(o), o);
  }

  public byte[] getValue() {
    return XapianJNI.ValueIterator_getValue(swigCPtr, this);
  }

}
